name: Latest blog post workflow
on:
  schedule: # Запускати автоматично раз на добу
    - cron: '0 0 * * *'
  workflow_dispatch: # Або можна запустити вручну з вкладки Actions

permissions:
  contents: write # Даємо дозвіл на оновлення README файлу

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # ТУТ ВАЖЛИВО: Заміни 'toyo12312' на свій точний username в dev.to, якщо він інший!
          feed_list: "https://dev.to/feed/nexus_ecosystem"
          
